### ISSUE TITLE
Support: How do I use docker-compose instead of faas-cli to deploy functions to Swarm?

### ISSUE THREAD

**Issue by dottgonzo** [openfaas/faas#1005]
Hi, i'm starting to evaluate openfaas for our company. For our infrastructures we need to have declarative and portable stack files so we can easy port them on every cluster. For this reason we are not using the faas-cli, we are trying to use openfaas functions by deploying them with stack files. For example:

```
version: '3.3'


networks:
  func_functions:
    external: true


services:
  nodeinfo:
    image: functions/nodeinfo:latest
    networks:
      - func_functions
    environment:
      fprocess: 'node main.js'
    labels:
      - function=true
      - "com.openfaas.scale.min=2"
      - "com.openfaas.scale.max=10"
```

## Expected Behaviour

we expect to see that functions ready and working (and it is ok) we expect also to see the functions replicated and with the auto scaling feature

## Current Behaviour

unfortunately it seems that if we deploy the functions by the stack file (for example by the one provided in this example) they don't scale and starts with 1 replica instead of 2 as configured, 

```
docker service ls | grep faasfun
poao468e5xdi        faasfunctions_nodeinfo      replicated          1/1                 functions/nodeinfo:latest
```
(the ui show replica 1 also)

how to declare scaling functionality on a function stack file?

the mission is to scale from 0, probably adding zero_scale=true to the environment variables of gateway as described on the openfaas docs: "set zero_scale to true for the gateway"
