### ISSUE TITLE
Question on limits for a Swarm cluster

### ISSUE THREAD

**Issue by pawelmarkowski** [openfaas/faas#1026]
Configuration attached below does not be reflected in 

docker service inspect hello

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  hello:
    lang: python3
    handler: ./hello
    image: hello:latest
    labels:
        "com.openfaas.scale.min": "2"
        # "com.openfaas.scale.max": "40"
    limits:
      cpu: 1000m
      # memory: 1000m
    requests:
      cpu: 1000m
      # memory: 400m
```

currently inspect returns "Resources": {}, I will paste below results from the code with uncommented memory params.

```
limits:
      cpu: 1000m
      memory: 1000m
requests:
      cpu: 1000m
      memory: 400m
```

## Expected Behaviour
Reservations for CPU in a service parameters

## Current Behaviour

> "Resources": {                                                                                                                                
>                     "Limits": {                                                                                                                               
>                         "MemoryBytes": 1048576000                                                                                                             
>                     },
>                     "Reservations": {
>                         "MemoryBytes": 419430400
>                     }                                 
>                 },

## Steps to Reproduce (for bugs)

1. faas-cli new --lang python3 hello
2. update hello.yml file
3. faas-cli build -f hello.yml
4. faas-cli deploy -f hello.yml

## Your Environment

CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.9.11
 sha:     78a4584019a2a5d86b606a00b4fba979930cc2a7
 commit:  Add sha256 hashgen for watchdog to ci config

Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.5.0 
 sha:           4269ab15673ad883bfdce4df47c055588e8e86b2

* Docker version `docker version` Version:           18.09.0

* Operating System and version (e.g. Linux, Windows, MacOS): Fedora

**Comment by pawelmarkowski** [comment]
IMO it is caused by different notation in CPU limits / requests in a docker swarm
it is not cpu: 1000m but **cpus**: 0.5

**Comment by alexellis** [comment]
Derek add label: support

**Comment by alexellis** [comment]
Derek add label: question

**Comment by alexellis** [comment]
https://github.com/openfaas/faas/issues/1026#issuecomment-453748305

Sounds like it might be right. Where did you get the values from that you used?

**Comment by pawelmarkowski** [comment]
I used config described in the docs https://docs.openfaas.com/reference/yaml/#function-memorycpu-limits

I checked version with:
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  hello:
    lang: python3
    handler: ./hello
    image: hello:latest
    readonly_root_filesystem: true
    environment:
      read_timeout: 3600s
      write_timeout: 3600s
    labels:
        "com.openfaas.scale.min": "2"
        # "com.openfaas.scale.max": "40"
    limits:
      cpus: 1
      memory: 1000m
    requests:
      cpus: 0.5
      memory: 400m
```

and the result in my local swarm is the same

> 
> "Resources": {
>                     "Limits": {
>                         "MemoryBytes": 1048576000
>                     },
>                     "Reservations": {
>                         "MemoryBytes": 419430400
>                     }
>                 },

what is proper way to limit cpus for the function if I use OpenFaaS and swarm? I was trying different combinations :)

**Comment by alexellis** [comment]
There are links on the page for both systems so that you can pick the correct option.

Here's the link from through page for Swarm https://docs.docker.com/config/containers/resource_constraints/

Alex

**Comment by pawelmarkowski** [comment]
Yes I know I wanted to add it in subcomment ;) https://docs.docker.com/config/containers/resource_constraints/ - but even if I use cpus option it does not work in OpenFaaS as you can see in my previous comment. (I have check cpu-period and so on also ...)

**Comment by alexellis** [comment]
The code and docs say "cpu" is the name of the field but your example says "cpus". I'm guessing that may be the problem?

https://github.com/openfaas/faas-cli/blob/master/stack/schema.go

Alex

**Comment by pawelmarkowski** [comment]
Yes in L61, I used cpu also as you can see on my first post. So it sounds like a bug in OpenFaaS - do you agree?

**Comment by alexellis** [comment]
The example you are using is wrong and can't work:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  hello:
    lang: python3
    handler: ./hello
    image: hello:latest
    readonly_root_filesystem: true
    environment:
      read_timeout: 3600s
      write_timeout: 3600s
    labels:
        "com.openfaas.scale.min": "2"
        # "com.openfaas.scale.max": "40"
    limits:
      cpus: 1
      memory: 1000m
    requests:
      cpus: 0.5
      memory: 400m
```

If there were an issue it would be with the openfaas/faas-swarm repo.

Alex
