### ISSUE TITLE
Proposal: Support multiple-revisions of functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1075]
Support multiple-revisions of functions

## Description

We should consider how to enable / support multiple-revisions of OpenFaaS functions. This is currently done by changing the name of the function before deployment.

If possible we could use a new feature-flag (for backwards compatibility) and conventions on the Docker image tag to support multiple concurrent versions of functions.

Imagine three different git commits and image tags defined in your stack.yml file:

```
functions:
  # version allows multiple slash commands in one comment
  name: derek
  image: derek:ef5ja
 
functions:
  # version has rebase command enabled
  name: derek
  image: derek:ffa3j

functions:  
  # version represents latest stable release, indicated via sem-ver
  name: derek
  image: derek:0.6.0 
```

This would produce 3 endpoints when deployed:

```
/function/derek-dev
/function/derek-ffa3j
/function/derek-0.6.0
```

We may want to then add an additional route like `/release` or `/revision` which can make use of "smart" aliases:

```
/release/derek/dev/    latest SHA   (ef5ja)
/release/derek/ffa3j/  other  SHA   (ffa3j)
/release/derek/0.6.0/  specific semver
/release/derek/0.6.1/   specific semver
/release/derek/  latest semver (0.6.1)
```

When we have two `semver` versions we can order these using a semver sort so that `/release/derek/` points to `0.6.1`.

Ideas for feature: Alex / Stefan

**Comment by burtonr** [comment]
I think it's important to keep the URL path the same for current/latest function versions.

`gateway.openfaas.com/function/derek` should always point to the most recent version available. I'm not certain how to accomplish this exactly. It could be an additional label `latest_function_version: true` and the label would need to be removed once another function of the same name is deployed.

For routing to a specific version, we could add the version to the route:
`gateway.openfaas.com/function/derek/ffa3j` in order to "lock" some outside application to a specific version.

The proxy should remove the version from the route when forwarding to the function to avoid forcing the individual functions to know if there is a version attached so that we don't break the path inside the functions. 

Behind the scenes, we could use labels to identify the version of the function. That could be created automatically when the function is deployed by taking the label from the container image and creating a label.

There is also the question of how does the deploy work with this in place? Would this mean that the users would need to explicitly remove all the containers themselves? Could we implement some sort of `prune` command that would clear out all but the latest version of the function?
I worry a little about having a lot of containers being deployed while testing/development that may cause issues...

**Comment by noppen** [comment]
Very much in favour of managed versioning of functions. Ideally the latest on the same endpoint or at least a softlink endpoint that lands you on the last deployed iteration of a function. Under ideal circumstances you would also have a rollback mechanism that allows you to determine a fixed endpoint of a previous version you know your dependent application worked well with. For interoperability as well as migration in our environment this would be extremely useful.

**Comment by LucasRoesler** [comment]
I like this idea.  

With respect to automating smart aliases, i see how the default/latest path could be implemented for  semver but not with shas.  Wouldn't it be easier to add an `alias` property to allow the user to manager these aliases. The "default" path would be either the last or the first found in the stack file. So, 

```yaml
functions: 
    # version allows multiple slash commands in one comment 
    name: derek 
    image: derek:ef5ja 
    
functions: 
    # version has rebase command enabled 
    name: derek 
    image: derek:ffa3j 
    
functions: 
    # version represents latest stable release, indicated via sem-ver 
    name: derek 
    image: derek:0.6.0
```
you would get this by default (assuming last in takes the default) 
```
/function/derek-ef5ja 
/function/derek-ffa3j 
/function/derek-0.6.0
/function/derek # aliases /function/derek-0.6.0
```

but the user could override this using 

```yaml
functions: 
    # version allows multiple slash commands in one comment 
    name: derek 
    image: derek:ef5ja 
    alias:
        - derek-latest
    
functions: 
    # version has rebase command enabled 
    name: derek 
    image: derek:ffa3j 
    alias:
        - derek-feature-branch
    
functions: 
    # version represents latest stable release, indicated via sem-ver 
    name: derek 
    image: derek:0.6.0
    alias:
         - derek-stable
```


```
/function/derek-ef5ja 
/function/derek-ffa3j 
/function/derek-0.6.0
/function/derek-stable # aliases /function/derek-0.6.0
/function/derek-feature-branch # aliases /function/derek-ffa3j
/function/derek # aliases /function/derek-ef5ja
```
