### ISSUE TITLE
Question about function duration

### ISSUE THREAD

**Issue by xumingxue** [openfaas/faas#1193]
I created functions that needed to last for a period of time(mostly several minutes). But I found that the duration of each function would not exceed 1 minute. Is there any option or parameter to be set to cancel this limitation?

**Comment by burtonr** [comment]
Be sure to adjust the timeout settings in both the Gateway, as well as your specific function.

Details can be found here: https://docs.openfaas.com/deployment/troubleshooting/#timeouts

**Comment by xumingxue** [comment]
> Be sure to adjust the timeout settings in both the Gateway, as well as your specific function.
> 
> Details can be found here: https://docs.openfaas.com/deployment/troubleshooting/#timeouts

Thank you for your reply:) I have add environment variables in the .yml file as mentioned in your link page like
...
functions:
  func:
    lang: python3
    handler: ./func
    image: mydockeraccount/func:latest
    environment:
      read_timeout: "100s"
      write_timeout: "100s"
      upstream_timeout: "90s"
      read_timeout: 100s
      write_timeout: 100s
      exec_timeout: 100s

and edit my function

**Comment by xumingxue** [comment]
> Be sure to adjust the timeout settings in both the Gateway, as well as your specific function.
> 
> Details can be found here: https://docs.openfaas.com/deployment/troubleshooting/#timeouts

Thank you for your quick reply:) I had a test function and added environment variables in the .yml file as mentioned in your link page like

```
provider:
  name: faas
  gateway: http://192.168.99.101:31112
functions:
  func:
    lang: python3
    handler: ./func
    image: mydockeraccount/func:latest
    environment:
      read_timeout: "100s"
      write_timeout: "100s"
      upstream_timeout: "90s"
      read_timeout: 100s
      write_timeout: 100s
      exec_timeout: 100s
```
and edited my python function like
```
import time
def handle(req):
    sleep_duration =req
    preSleep = "Starting to sleep for "+sleep_duration.__str__()
    time.sleep(int(sleep_duration))  # Sleep for a number of seconds
    postSleep = "Finished the sleep"
    print("Done!")
    return preSleep + "\n" + postSleep

```
however the function still stopped at about 1 minute. I work with openfaas deployed on minikube. Is there something I missed? Thank you!
