### ISSUE TITLE
Question about function duration

### ISSUE THREAD

**Issue by xumingxue** [openfaas/faas#1196]
## Expected Behaviour

Create functions that needs to last for a period of time(e.g. several minutes or hours).

## Current Behaviour

The duration of each function cannot exceed 1 minute.

## Possible Solution and Result

Edit .yml file as mentioned in [https://docs.openfaas.com/deployment/troubleshooting/#timeouts](url)
For example, edit my python function like
```
import time
def handle(req):
    sleep_duration =req
    preSleep = "Starting to sleep for "+sleep_duration.__str__()
    time.sleep(int(sleep_duration))  # Sleep for a number of seconds
    postSleep = "Finished the sleep"
    print("Done!")
    return preSleep + "\n" + postSleep
```
And its corresponding deployment file func.yml is 
```
provider:
  name: faas
  gateway: http://192.168.99.101:31112
functions:
  func:
    lang: python3
    handler: ./func
    image: mydockeraccount/func:latest
    environment:
      read_timeout: "100s"
      write_timeout: "100s"
      upstream_timeout: "90s"
      read_timeout: 100s
      write_timeout: 100s
      exec_timeout: 100s
```
However, its invoke duration still cannot exceed 1 minute, even when the request `req`  is "90"(it means that I hope the function lasts for 90 seconds). 
Is there something I missed? 
## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? No

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

I deployed openfaas on minikube.
