### ISSUE TITLE
Feature request: mount secret as environment variable

### ISSUE THREAD

**Issue by jonatasbaldin** [openfaas/faas#1302]
## Expected Behaviour
Being able to mount the decoded secret content as an environment variable instead of a file.

## Current Behaviour
The secret system used by OpenFaaS only mounts secrets as files.

## Possible Solution
Introduce new way of defining the secrets in the `stack.yml` file and, somehow, inject them into an env var. Here are some examples to illustrate:

*Example 1:*
- Add a "type" to a secret, enabling more types in the future 
- Possible breaks backwards comparability

```yaml
secrets:
  - name: payload-secret
    mount_type: file
    path: /var/openfaas/secret/payload-secret

  - name: payload-secret
    mount_type: env_var
    path: PAYLOAD_SECRET
```

*Example 2:*
```yaml
# - Keep `secrets` as is
secrets:
  - payload-secret

# Add a new keyword for environment variable secrets
env_secrets:
  - name: payload-secret
    env_var: PAYLOAD_SECRET
```

## Context
Dynamically configuring applications with environment variables tends to be easier than reading files. Usually languages and frameworks come with friendly and easy ways to access these vars. 

Also, accessing env vars is probably faster than reading a file, since no file IO is necessary.

Thanks 🚀
