### ISSUE TITLE
Proposal Support setting build args via yaml

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas#1304]
This was originally proposed in https://github.com/openfaas/faas-cli/issues/262 but was eventually implemented as flags on the `faas-cli`.  This CLI behavior is documented here https://docs.openfaas.com/cli/build/#30-pass-custom-build-arguments

To ensure reproducible and portable builds, we should support supplying build args via the YAML stack file.

## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

It should be possible for both of these commands to produce the same build

```sh
faas-cli build
faas-cli build --build-arg ARGNAME1=argvalue1
```

## Current Behaviour

The only way to set build args is via tha CLI

```sh
faas-cli build --build-arg ARGNAME1=argvalue1
```

## Possible Solution

Allow specifying a map of build args per function in the stack yaml, for example

```yaml
functions:
  url-ping:
    lang: python
    handler: ./sample/url-ping
    image: alexellis2/faas-urlping
    build_arg:
        cookies: "yup"
        pie: "please"
        brownies: "of_course"
```
