### ISSUE TITLE
Openfaas ignores yml timeout definitions over 60 seconds.. whether through UI or function URL

### ISSUE THREAD

**Issue by beviah** [openfaas/faas#1434]
OpenFaas ignores all timetout if they go over 50 seconds. 

in yml file:
 ```
    read_timeout: 300s
    write_timeout: 300s
    upstream_timeout: 300s
    exec_timeout: 300s
    environment:
      read_timeout: 300s
      write_timeout: 300s
      upstream_timeout: 300s
      exec_timeout: 300s
```

This may be relevant: https://github.com/openfaas/faas/issues/608#issuecomment-376818597
