### ISSUE TITLE
Istio support request

### ISSUE THREAD

**Issue by kpiyush17** [openfaas/faas#1554]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ ] Read/searched [the docs](https://docs.openfaas.com/)
- [ ] Searched [past issues](/issues)

Hi, I have deployed openfaas in Kubernetes with istio enabled. I have deployed the gateways and virtualservice also.

Openfaas deploy command:
```
helm upgrade openfaas --install openfaas/openfaas \
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn \
    --set generateBasicAuth=true \
    --set gateway.replicas=2 \
    --set faasIdler.dryRun=false \
    --set async=false
```
I have exposed the gateway using istio-ingressgateway. However, I am getting 404 errors while accessing `/system/function/<function-name>` endpoint. I checked another endpoint `/system/functions` and it is working fine. 

Is the 404 expected? Do, I have to add some other route?

Virtualservice:

```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openfaasgw
spec:
  hosts:
  - "openfaas.example.com"
  - "gateway.openfaas.svc.cluster.local"
  - "prometheus.openfaas.svc.cluster.local"
  gateways:
  - openfaas-gateway
  http:
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        host: prometheus.openfaas.svc.cluster.local
        port:
          number: 9090
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gateway.openfaas.svc.cluster.local
        port:
          number: 8080
```
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.8

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

If using Swarm, run the following and include the output:

```
curl -sLS https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh | bash
```

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.
