### ISSUE TITLE
Using multi line environment variable in stack.yml results in an error

### ISSUE THREAD

**Issue by amitlevy21** [openfaas/faas#1611]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I have a multi line environment variable `$RSA` containing RSA key that I need to pass as a build argument to Docker.
The command `faas-cli build / up --build-arg RSA=${RSA}` works. However if I tried to the following it doesn't:
```yaml
# stack.yml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  myfn:
    lang: dockerfile
    handler: .
    image: localhost:5000/myfn:latest
    build_args:
      RSA: ${RSA}

```

## Expected Behaviour
`RSA` build argument should contain the environment variable value from my shell.

## Current Behaviour

The following error occurs:
```sh
❯ faas-cli up
Error with YAML file
Yaml: line 15: could not find expected ':'
```

## Possible Solution

I can use the same environment variable without issues in `docker-compose.yml`:
```yaml
myservice:
    build:
      context: .
      args:
        RSA: ${RSA}
```

## Steps to Reproduce (for bugs)

1. `faas-cli new --lang python3 myfn`
2. Rename `myfn.yml` to `stack.yml`
3. Edit `stack.yml` and replace with the given configuration above.
4. `export RSA=$(cat $HOME/.ssh/my_rsa)`
5. `faas-cli up`
6. Error should be shown.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
❯ faas-cli version

CLI:
 commit:  598336a0cad38a79d5466e6a3a9aebab4fc61ba9
 version: 0.12.21

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.20.2
 sha:     9bbb25e3c7c4cc5cd355edb3a122f8c7812e32db
 commit:  Fix a bug that caused the services list to keep growing

Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.12.9
 sha:           c402b912ce21f0bf01bc3aa45ebc330decc41ac5

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```sh
❯ docker --version
Docker version 19.03.11, build 42e35e6
```

* Are you using Kubernetes or faasd? K8s

* Operating System and version (e.g. Linux, Windows, MacOS): Linux (Fedora 32)

* Code example or link to GitHub repo or gist to reproduce problem: Everything provide in the issue

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting): The logs are from the cli so not providing for now unless request.
