### ISSUE TITLE
[Feature Request] Asynchronous Concurrency Limiting

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas#1618]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

If you set `max_inflight` on an async function's `of-watchdog`, you might naturally assume that a queue worker will handle the case when it tries to invoke a function on a pod that has reached its `max_inflight`, and would therefore send the request to a different pod, if possible.

## Current Behaviour

If you use a sync function and set `of-watchdog.max_inflight`  on an of-watchdog pod, and invoke that function above that amount (assuming 1 pod), you will as expected get `429`s letting you know that you’ve sent more requests than you’ve configured to be allowed to be worked on per pod.

However, the same behavior exists when using async functions; if you set `queue.max_inflight=5`  and `of-watchdog.max_inflight=1` , if the queue worker attempts to send that request to a pod that already has 1 invocation in progress, it receives the same `429` and forwards it off to the gateway as your official response. I propose that a queue worker would instead retry on `429`s, or a similar retry mechanism (as a `429` is a completely valid response for functions at the moment).

## Possible Solution

Having a queue worker retry to a different pod (if possible), potentially with incremental backoff.

I’m also open to a completely different mechanism, and willing to implement.

## Context

Having a queue worker retry if it attempts to invoke a pod that’s already hit its maximum concurrent invocations would probably be the last technical hurdle for me to get async autoscaling working well for “long-running” functions, and therefore I'd say this issue is related to #657.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.21
* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.2
* Are you using Kubernetes or faasd? kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS): MacOS/Linux
* Code example or link to GitHub repo or gist to reproduce problem:
* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

**Comment by alexellis** [comment]
Thanks for the suggestion @kevin-lindsay-1 - we will prioritise your request on the roadmap and have a look into it, in due course.

**Comment by derekyyyan** [comment]
Hi, just wanted to chime in as I'm also running into this exact scenario.

One thing I noticed is that whatever is load balancing the requests to the function pods does not always send the request to an idle pod. For example, if I have 2 pods of a function with `max_inflight=1`, and then I invoke the function asynchronously twice, there is a chance that both requests go to the same pod, resulting in a `HTTP 429` response for one of the requests.

It maybe worthwhile to implement some kind of monitor for when a function pod is "at capacity", i.e. handling `max_inflight` number of requests concurrently, and the queue worker can simply use the monitor to wait for a pod to become available, instead of blindly retrying with backoff. (I don't know if this is realistically possible.)

**Comment by alexellis** [comment]
Sounds like you may not have direct_functions set to false..

**Comment by derekyyyan** [comment]
I can set `direct_functions` explicitly to false, although the docs for the faas-netes helm chart suggests that it already defaults to false.

I'm also not using Linkerd or Istio.

I'll try replicating the problem when I get the chance, but here's my helm chart settings if that helps. I'm on version 7.1.0 so should be mostly the same as the latest.

<details>
  <summary>values.yaml</summary>

```yaml
functionNamespace: openfaas-fn
httpProbe: false
psp: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-private
    cert-manager.io/cluster-issuer: letsencrypt-production
  tls:
    - hosts:
      - <redacted>
      secretName: openfaas-tls-cert
  hosts:
    - host: <redacted>
      serviceName: gateway
      servicePort: 8080
      path: /
faasnetes:
  httpProbe: false
  imagePullPolicy: Always
  setNonRootUser: true
gateway:
  replicas: 2
queueWorker:
  replicas: 10
  ackWait: 1m
faasIdler:
  create: false
```
</details>
