### ISSUE TITLE
Unable to enumerate functions deployed to non-standard namespace

### ISSUE THREAD

**Issue by zjpiazza** [openfaas/faas#1648]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
User should be able to list functions deployed in alternative namespaces using `faas-cli ls -n [namespace]`

## Current Behaviour
Function is deployed in non-standard namespace, but is not returned by the faas-cli list command. Namespace has been properly annotated with "openfaas=1" via kubectl. Role and RoleBinding have also been created. The deployment was definitely accepted by the gateway and the k8s scheduler created an associated deployment for the function. However I cannot list it via the cli or invoke via curl.

## Steps to Reproduce (for bugs)
1. Create secondary namespace for functions
2. Create Role and RoleBinding in new namespace for openfaas-controller to operate in newly created namespace
3. Deploy function to newly created namespace
4. Execute `faas-cli ls -n [namespace]` and no results are returned

## Context
Trying to setup multi tenant OpenFaaS installation so having fully working support for namespaces is criticial

## Your Environment
* FaaS-CLI version:
0.13.8

* Docker version:
Client 19.03.12

* OpenFaaS platform:
Kubernetes

* Operating System and version:
Windows 10 19041.804

**Comment by alexellis** [comment]
When tested the multiple namespaces feature just now, it worked as expected. Can you confirm exactly what patches you've made to OpenFaaS and how you installed it?

A ClusterRole is given in the helm chart for multiple namespaces, but it sounds like you're not using it?

Closing this for now, as it's a non-standard use of openfaas and falls more into technical support than a bug. Please do feel free to keep commenting. If you give us the full steps for a repro using our helm chart, or your forked version / manifests, someone may take a look.

Alex

**Comment by LucasRoesler** [comment]
Hi @zjpiazza i am actually working on the certifier support for multiple namespaces right now and this is a test case they isn't covered. I will make sure we get it into the tests and of course look into this issue directly along with it.

**Comment by zjpiazza** [comment]
Got it. I guess I'm a bit confused because in the documentation section namespaces, it specifically calls out this feature request on GH which has since been marked as closed ([multiple namespace support](https://github.com/openfaas/faas-netes/issues/511)) so I assumed this functionality had been implemented already. If you cannot manage functions beyond deployment into another namespace, maybe this should be called out explicitly in the namespace doc page.

**Comment by zjpiazza** [comment]
Sorry did not see the update from Alex. It says specifically that you can either use the cluster role or create Role & RoleBinding for each new namespace. We are running this in a shared environment so I thought the ClusterRole might raise security concerns so I opted for the least privledged approach. If you're saying ClusterRole for sure works, I'll give that a shot. Thanks.

**Comment by alexellis** [comment]
The functionality has been completed and does work as designed. I'll let Lucas comment again as I think it's just caused confusion.

Alex

**Comment by alexellis** [comment]
You are right that the docs page also mentions RBAC permissions for multi-tenancy, but we do not provide a tested set other than with the ClusterRole. If you need help debugging your cluster and patches, feel free to [contact support](https://openfaas.com/support/) about how we can help.

You will likely [see some errors in the logs](https://docs.openfaas.com/deployment/troubleshooting/) if you do decide to stay with your current approach.

What is documented is tested and freely available. It's open source, so you can modify it, but we cannot give deep technical support for custom and bespoke solutions that fall out of that.

For enterprise-grade custom solutions we are happy for you to [contact us](https://openfaas.com/support) to discuss a separate arrangement where we can specifically find the resources to help you.

**Comment by alexellis** [comment]
Using bespoke roles and bindings still needs the cluster role flag from what I can see. If you can confirm that, we'd accept a PR to the docs 

https://github.com/openfaas/faas-netes/blob/718ff2736224b66cafbaad3d1dd25cac3fd13d0b/main.go#L118

**Comment by alexellis** [comment]
Digging a bit further, you will need a ClusterRole if you want to list deployments across multiple namespaces.

Perhaps you can create a read-only ClusterRole like the one we provide, then create additional namespace-scoped Role/Bindings for the write access.

At that point you're doing an awful lot of work and may find that most operators that work across multiple namespaces also use ClusterRoles. Dig around on the Operator Hub perhaps?

**Comment by alexellis** [comment]
This appears to work in this order / arrangement:

```
alex@alex-nuc8:~$ faas-cli namespaces
Namespaces:
 - dev
 - openfaas-fn
alex@alex-nuc8:~$ faas-cli list -n dev
Function                      	Invocations    	Replicas
alex@alex-nuc8:~$ faas-cli list -n openfaas-fn
Function                      	Invocations    	Replicas
alex@alex-nuc8:~$ faas-cli store deploy nodeinfo

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/nodeinfo

alex@alex-nuc8:~$ faas-cli store deploy figlet -n dev

Deployed. 202 Accepted.
URL: http://127.0.0.1:8080/function/figlet.dev

alex@alex-nuc8:~$ curl http://127.0.0.1:8080/function/nodeinfo
Hostname: nodeinfo-857d9c469b-6pbmm

Arch: x64
CPUs: 8
Total mem: 32035MB
Platform: linux
Uptime: 698929
alex@alex-nuc8:~$ curl -d hi http://127.0.0.1:8080/function/figlet.dev
 _     _ 
| |__ (_)
| '_ \| |
| | | | |
|_| |_|_|
         
alex@alex-nuc8:~$ 
```

Example:

```yaml
# -- After arkade install --clusterrole

# -- Create namespace dev
# -- Make ClusterRole read-only

# -- Create Role and RoleBinding for dev namespace

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openfaas: "1"
  name: dev
spec: {}
---
```

Then:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2021-05-04T19:17:31Z"
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-7.2.8
    component: faas-controller
    heritage: Helm
    release: openfaas
  name: openfaas-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfaas.com
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2021-05-04T19:17:31Z"
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-7.2.8
    component: faas-controller
    heritage: Helm
    release: openfaas
  name: openfaas-controller-dev
  namespace: openfaas
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfaas.com
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2021-05-04T19:17:31Z"
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-7.2.8
    component: faas-controller
    heritage: Helm
    release: openfaas
  name: openfaas-controller-dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfaas-controller
subjects:
- kind: ServiceAccount
  name: openfaas-controller
  namespace: openfaas

```

**Comment by alexellis** [comment]
This example seems to work for me locally. Without the writable Role/Binding the faas-cli deploy fails, then adding it makes it pass.

```yaml
# -- After arkade install --clusterrole

# -- Create namespace dev
# -- Make ClusterRole read-only

# -- Create Role and RoleBinding for dev namespace

---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openfaas: "1"
  name: dev
spec: {}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  creationTimestamp: "2021-05-04T19:17:31Z"
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-7.2.8
    component: faas-controller
    heritage: Helm
    release: openfaas
  name: openfaas-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfaas.com
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  labels:
    app: openfaas
    component: faas-controller
  name: openfaas-controller-dev
  namespace: dev
rules:
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - endpoints
  verbs:
  - get
  - list
  - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: openfaas
    component: faas-controller
  name: openfaas-controller-dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfaas-controller-dev
subjects:
- kind: ServiceAccount
  name: openfaas-controller
  namespace: openfaas

```
