### ISSUE TITLE
using nvidia gpu.

### ISSUE THREAD

**Issue by HyeyeonKoo** [openfaas/faas#1695]
Hello, Thank you for the nice work.
I am trying to use OpenFaaS with GPU. But it is not easy. 
So, I will be very appreciate if you give me some advices.

**Environments**
* FaaS-CLI version ( Full output from: `faas-cli version` ):  0.14.1
* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.12
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? Minikube 1.25.1
* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
* plus,
I install nvidia-docker from fallowing [this link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html)
and,
I make minikube recognize gpu in cluster from fallowing [this link](https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/). So, cluster recognize it well.
```
$ kubectl get nodes "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu"
NAME                       GPU
[SYSTEM_NAME]         1
```
and, also working well in nvidia/cuda container.

**But, It didn't work in OpenFaaS funtion. How can I OpenFaaS Function recognize GPU. Do I need to edit docker file?**
Please, help.

**Comment by alexellis** [comment]
Hi @HyeyeonKoo thanks for your interest in OpenFaaS

You will need to fill out the whole issue template and ideally provide us with a code example too.

https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

Let me know if you are going to do that or whether you want to close the issue.

If this is for your employer, feel free to reach out about [commercial support](https://openfaas.com/support/).

Alex

**Comment by HyeyeonKoo** [comment]
Thank you for the answer. I try to fill the form again.



## My actions before raising this issue
- [X] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [X] Read/searched [the docs](https://docs.openfaas.com/)
- [X] Searched [past issues](/issues)


I found an issue that similar to the one I was looking for : https://github.com/openfaas/faas/issues/639
In this issue, I found that using GPU with openfaas using nvidia-docker.
So, I install nvidia-docker, and GPU is successfully recognized in minikube's contatiner.

## Expected Behaviour


I want to use GPU in OpenFaaS Funtion with pytorch.

## Current Behaviour


GPU is not available using pytorch in OpenFaaS function.

## Are you a GitHub Sponsor (Yes/No?)


Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No
I don't have enough skills to support yet. I try to learn now and someday I want to be one of sponsors.

## List All Possible Solutions and Workarounds



Is there a chance to make the GPU available with changing function's DockerFile or YAML?


## Which Solution Do You Recommend?


## Steps to Reproduce (for bugs)


1. make function
```
$ mkdir gpu-is-available && cd gpu-is-available
$ faas-cli new --lang python3-debian gpu-is-available 
```
2. gpu-is-available/requirements.txt
```
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.10.1+cu113
numpy
```
3. gpu-is-available/handle.py
```
import torch

def handle(req):
    available = ""

    if torch.cuda.is_available():
        available = "GPU is available." + "\n" \
                    + "Device count is " + str(torch.cuda.device_count()) + "\n" \
                    + "Device name is " + torch.cuda.get_device_name(0)
    else:
        available = "GPU is not available. Sorry."

    return available
```
4. build, push, deploy
```
faas-cli up -f ./gpu-is-available.yml
```
5. invoke => *GPU is not recognized*
```
$ echo | faas-cli invoke gpu-is-available
```
```
GPU is not available. Sorry.
```

## Context


I try to service deep learning model inference like sentiment analysis.


## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.14.1

* Docker version `docker version` (e.g. Docker 17.0.05 ): 20.10.12

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)? Minikube 1.25.1

* Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04

* Code example or link to GitHub repo or gist to reproduce problem: I demonstrate it above.

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
I install nvidia-docker from fallowing [this link](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html)
and,
I make minikube recognize gpu in cluster from fallowing [this link](https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/). So, cluster recognize it well.

**Comment by LucasRoesler** [comment]
@HyeyeonKoo at least one approach to this is partially described here https://docs.openfaas.com/reference/profiles/#use-tolerations-and-affinity-to-separate-workloads

Using the profiles feature you can ensure that the function is running on a node with a GPU.

It might be possible with [constraints](https://docs.openfaas.com/reference/yaml/#function-constraints) but I think the profiles approach is more accurate

**Comment by HyeyeonKoo** [comment]
Thank you for answering. 
I tried to follow the instruction, but got some problem.


first, when I create a profile with YAML, error occurred.
```
error: error validating "STDIN": error validating data: [ValidationError(Profile.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[1]): unknown field "key" in com.openfaas.v1.Profile.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms, ValidationError(Profile.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[1]): unknown field "operator" in com.openfaas.v1.Profile.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms, ValidationError(Profile.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[1]): unknown field "values" in com.openfaas.v1.Profile.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms]; if you choose to ignore these errors, turn validation off with --validate=false
``` 

So, I apply it with ```--validate=false``` flag. After that, I found the pod's status is pending.
```
NAME                                   READY   STATUS    RESTARTS   AGE
...
gpu-is-available-66b976994c-qdxsv      0/1     Pending   0          24s
...
```

Can you give me some more advice with this problem, please?

**Comment by LucasRoesler** [comment]
It looks like a validation error, without seeing that profile yaml you used it is pretty hard to say for sure.

My guess from rereading the docs, is that it is a yaml indentation error

The docs have this (which is wrong) 
```yaml
kind: Profile
apiVersion: openfaas.com/v1
metadata:
  name: withgpu
  namespace: openfaas
spec:
    tolerations:
    - key: "gpu"
      operator: "Exists"
      effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
            - key: gpu
              operator: In
              values:
              - installed
```

But it should probably be this 
```yaml
kind: Profile
apiVersion: openfaas.com/v1
metadata:
  name: withgpu
  namespace: openfaas
spec:
    tolerations:
    - key: "gpu"
      operator: "Exists"
      effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: In
                values:
                  - installed
```

It would really help to know the output from `kubectl version` and how you installed openfaas (via helm or arkade, what flags or values you use etc) and finally that Profile you tried to you.
