### ISSUE TITLE
Can't achieve anti-affinity between function replicas with Profiles

### ISSUE THREAD

**Issue by rpetrano** [openfaas/faas#1738]
## My actions before raising this issue
- [ X ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [ X ] Read/searched [the docs](https://docs.openfaas.com/)
- [ X ] Searched [past issues](/issues)

## Why do you need this?
I need to make sure replicas of the same function do not run on the same node. I can't.

## Expected Behaviour

I should be able to force replica pods of the same function deployment to be on the different nodes by using anti-affinity or Profiles, but I can't. To do so with a Profile I would need to know the name of the faas_function label of a function being deployed, like this:

```yaml
---
kind: Profile
apiVersion: openfaas.com/v1
metadata:
  name: antiaffinity
  namespace: openfaas
spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: faas_function
              operator: In
              values:
              - FUNCTION_NAME
          topologyKey: "kubernetes.io/hostname"
```

## Current Behaviour

I can do node affinity / tolerations. But I can't do pod to pod affinities.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ X ] No

## List All Possible Solutions and Workarounds

In my opinion the only solution is for OpenFaas to create a podAntiAffinity in the deployment yaml of a function. It means the function specification YAML file has to have options to fine tune the affinity/anti-affinity

Workarounds:

1. Create an openfaas-cli wrapper that creates an anti-affinity profile for each function, but that's ugly and is prone to errors.
2. Create a bash script to patch all deployments of a namespace with desired rules. Call this script after any openfaas deployment.

## Which Solution Do You Recommend?

Workaround #2. I wrote a bash script for it:

```bash
#!/bin/bash

patch() {
    name="$1"
    cat <<EOF
metadata:
  labels:
    patched_antiaffinity: "true"
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: faas_function
                operator: In
                values:
                - "${name}"
            topologyKey: "kubernetes.io/hostname"
EOF
}

query_namespace() {
    namespace="$1"
    script=$(cat <<-EOF
        .items[]
            | select(.metadata.labels.patched_antiaffinity != "true")
            | .spec.template.metadata.labels.faas_function
EOF
)
    kubectl get deployments -o json -n "$namespace" \
        | jq -r "$script"
}

for i in prod demo test dev; do
    n="fn-$i"
    to_patch=($(query_namespace "$n"))

    for j in "${to_patch[@]}"; do
        echo "Patching $n $j"

        kubectl patch deployment -n "$n" "$j" --patch-file <(patch "$j")
    done
done

```

## Steps to Reproduce (for bugs)

1. Want to create a deployment with multiple replicas having each replica on different node
2.
3.
4.

## Context
 
Making sure deployment replicas are not on the same node is crucial to ensure stability of a cluster in an event of a single-node failure.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
Helm chart 10.1.3

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.17

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Arch Linux
Linux 5.15.48-1-lts #1 SMP Thu, 16 Jun 2022 13:32:35 +0000 x86_64 GNU/Linux

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
