### ISSUE TITLE
Proposal: Support multiple different gateways with filtering options for function services

### ISSUE THREAD

**Issue by kinghuang** [openfaas/faas#175]
This proposal relates to #55.

The OpenFaaS API Gateway discovers function services in a Docker Swarm based on the presence of a `function` label (or the `func` label on external providers). This behaviour is problematic if there are multiple instances of the API Gateway running, where each gateway is meant to cover different sets of services.

For example, in a multi-tenant environment, there may be more than one API Gateway deployed within the same swarm for different purposes. Or, there may be multiple deployments of a single stack for different branches of development. Functions meant for a certain API Gateway “leak” into other gateways because individual gateways do not have the ability to determine which specific functions are meant for them.

There are several possible ways to support multiple instances of the API Gateway in a single swarm.

### A: Allow the `function` label to be customized

`function` is currently coded as a literal string in the gateway to filter for OpenFaaS functions. This could be made into a configurable item so that gateways can be set to look for custom labels.

Here's an example of a gateway and a function configured to use `custom_function` as a label for function services.

```
gateway:
    image: functions/gateway:latest-dev
    environment:
        faas_function_label: 'custom_function'

echoit:
    image: functions/alpine:health
    labels:
        custom_function: "true"
    environment:
        fprocess: "cat"
```

#### Pros

* Simple to change. The string `function` only appears in 4 places. A config can be added for something like `faas_fuctions_label` that defaults to `function` and is passed where needed.
* Functions can have multiple labels to associate themselves with multiple distinct gateways.

#### Cons

* A changing label key (as opposed to the label value) might not be desirable.

### B: Look for a specific value or pattern in the `function` label

The value of the `function` label is not considered when reading for function services in `MakeFunctionReader()`. It's typically set to `"true"` in examples. A config could be added to specify a value or pattern to match on. So, something like the following (from [gateway/reader.go#L41](https://github.com/alexellis/faas/blob/master/gateway/handlers/reader.go#L41)):

Before:
```
if len(service.Spec.TaskTemplate.ContainerSpec.Labels["function"]) > 0 {
```

After:
```
label_value := service.Spec.TaskTemplate.ContainerSpec.Labels["function"]
match, _ := regexp.MatchString(label_value_pattern, label_value)

if match {
```

A similar change would apply in `swarmwatcher.AttachSwarmWatcher()`. Here's an example service definition for gateway and a function.

```
gateway:
    image: functions/gateway:latest-dev
    environment:
        faas_label_value: 'some-custom-value'

echoit:
    image: functions/alpine:health
    labels:
        function: "some-custom-value"
    environment:
        fprocess: "cat"
```

#### Pros

* Simple to change.
* Using patterns for the label value could allow for interesting ways of selecting sets of function services.

#### Cons

* Not sure how you would come up with a value when creating a function service spec in `createhandler.makeSpec()`. It currently sets the label value to `"true"`.

### C: Filter based on the stack namespace

If we assume that the gateway and its function services are deployed as part of the same stack, the gateway service's `com.docker.stack.namespace` label could be matched against function services.

#### Pros

* As an option, this would be very convenient from a user standpoint for deployments where the gateway and service functions are together in the same stack.

#### Cons

* Not sure how this would work for external providers.

### D: Filter based on common networks

Function services could be filtered based on whether or not they share a common network with the gateway. Services that do not share a common network are not included.

#### Pros

* This probably makes sense for all deployments. If the gateway cannot communicate with a function service because there isn't a route between them, it can't work anyways.

#### Cons

* None?

## Effort

* Option A seems pretty simple. But, I'm not sure if it's a good idea.
* Option B is also pretty simple. We'd need to somehow generate a string to match the label pattern when creating services.
* Option C and D are already started on the [filter_networks](https://github.com/alexellis/faas/compare/filter_networks?expand=1) branch, I think. It'd need to be brought up to date and tested.

**Comment by kinghuang** [comment]
Another option that just occurred to me is to allow the gateway to be configured with arbitrary key-value matches on tags/labels. That would enable matching on stacks and any user-defined label.

The following would be the default behaviour.

```
gateway:
    image: functions/gateway:latest-dev
    environment:
        faas_function_constraint: 'function==true'

echoit:
    image: functions/alpine:health
    labels:
        function: "true"
    environment:
        fprocess: "cat"
```

A list of constraints could be passed.

```
gateway:
    image: functions/gateway:latest-dev
    environment:
        faas_function_constraint:
            - function==true
            - com.docker.stack.namespace==func
            - my_custom_key==my_custom_value

echoit:
    image: functions/alpine:health
    labels:
        function: "true"
        my_custom_key: my_custom_value
    environment:
        fprocess: "cat"
```
