### ISSUE TITLE
How to deploy execute program by faas-cli?

### ISSUE THREAD

**Issue by leenux** [openfaas/faas#209]
After deploy faas stack and success can access by localhost:8080/ui/, I already build execute program by host's go build and it isn't docker's
```$ curl localhost:8080/function/func_faas1```
The echo was null
## Expected Behaviour

Should return ```Hello!``` but return null

Need document about deploy bin execute.
## Steps to Reproduce (for bugs)

1.main.go
```
package main

import "fmt"

func main() {
	fmt.Println("Hello!")
}
```
2.``` go build``` success and faas1 put to current path
3.After download fwatchdog to current path
4.create Dockerfile
Dockerfile
```
FROM alpine:latest
ENTRYPOINT []

COPY fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

COPY faas1 /usr/bin/faas1
RUN chmod +x /usr/bin/faas1

ENV fprocess "/usr/bin/faas1"

EXPOSE 8080
CMD ["/usr/bin/fwatchdog"]
```
```docker build -t functions/faas1:latest .```
5.docker-compose.yml
```
version: "3.2"
services:
    # faas1
    faas1:
        image: functions/faas1:latest
        labels:
            function: "true"
        depends_on:
            - gateway
        networks:
            - functions
        environment:
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            placement:
                constraints:
                    - 'node.platform.os == linux'


networks:
    functions:
        driver: overlay
        # Docker does not support this option yet - maybe create outside of the stack and reference as "external"?
        #attachable: true
```
6.```docker stack deploy func --compose-file docker-compose.yml```
7.found the ```func_faas1``` by ```localhost:8080/ui/``` and invoke can see the ```Hello!```

8.```curl localhost:8080/function/func_faas1``` return null
## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 16.04 x64
* Link to your project or a code example to reproduce issue:
```
package main

import "fmt"

func main() {
	fmt.Println("Hello!")
}
```
