### ISSUE TITLE
'500 Internal Server Error' recieved when POSTing to function that has environment variables set in the YAML

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas#213]
I was trying out the `environment:` YAML element to set environment variables in the deployment file. However, it causes some problems for me. When I deploy the following function:

```
provider:
  name: faas
  gateway: http://localhost:8080

functions:
  gif-maker:
    lang: Dockerfile
    handler: ./gif-maker
    image: ems5311/gif-maker:latest
    environment:
      read_timeout: 65
      write_timeout: 65
      write_debug: false
```

When I go to use this function (`cat file.mp4 | faas-cli invoke -f file.yml`) I always get a `500 Internal Server Error` response from the function. When I remove the environment variables `read_timeout: 65` and `write_timeout: 65`, the function suddenly accepts requests and works just fine.

Strangely, I have another function deployed with `read_timeout:` and `write_timeout:` env variables set in the YAML, and it works fine.

Is this feature just not implemented yet?

Thanks,
Eric

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
**17.09.0-ce-rc1**
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
**Docker Swarm**
* Operating System and version (e.g. Linux, Windows, MacOS):
**Ubuntu 16.04**
* Link to your project or a code example to reproduce issue:
