### ISSUE TITLE
Backlog: User-configureable memory/RAM limits per function

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#239]
## Expected Behaviour

With some back-ends a hard-coded memory limit is needed - we should be able to set this at deployment time by passing additional parameters.

## Current Behaviour

Leave unbounded or set a hard-limit

## Possible Solution

For DC/OS in particular - memory limits need to be set - so we'd pass additional data in the Create/Deploy endpoint.

Individual providers can opt in or ignore the metadata. 

## Scope

* [ ] Kubernetes
* [ ] Docker Swarm

**Comment by austinfrey** [comment]
possibly related to https://github.com/openfaas/faas-cli/issues/143

**Comment by nenadilic84** [comment]
I'll start looking into this.
My suggestion would be to have a structure like this:
```
resources:
    limits:
        cpus: '0.001'
        memory: 50M
    reservations:
        cpus: '0.0001'
        memory: 20M
```
that will be propagated from the faas-cli, read from the `myfunctions.yml` or from a commandline arguments: `--limit-cpu`, `--limit-memory`, `--reserve-cpu`, `--reserve-memory`.
Then we can have implementations in the gateway for different backends.

If no one objects on this, I'll start working on it...
