### ISSUE TITLE
Proposal: Add CI/CD pipeline guideline or example

### ISSUE THREAD

**Issue by kenfdev** [openfaas/faas#295]
It would be nice to have a CI/CD pipeline guideline or example. 

## Expected Behaviour

* Push the Code
* Pipeline gets triggered
  * `faas-cli build`
  * `faas-cli deploy` -> [Deploy to Temporary Test Environment]
  * Test the Function
  * If Test passes
    * `faas-cli push` and update the registry
    * Optionally trigger a deploy to external environment (dev, prod, wherever)
* Pipeline Finish

## Possible Solution

I was talking with @alexellis and decided to create a pipeline with travis-ci.
Here's a sample `.travis.yml` I wrote, testing with node.js:

```yaml
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

cache: yarn

before_install:
  # installing newer docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # installing the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh
  - docker swarm init
  - ./ci-setup.sh

script:
  - yarn test

after_script:
  - docker swarm leave -f

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    faas-cli push -f echo.yml
    fi
  # you can deploy to a dev or prod (whatever) environment at this stage
```

The complete repo is uploaded here:
https://github.com/kenfdev/faas-echo

Here's a diagram of the pipeline:

![openfaas-travis-ci](https://user-images.githubusercontent.com/3941889/31572976-076770ee-b0ed-11e7-8829-c6790d7b1ed0.png)

## Context

The pipeline above works but there are some considerations I have which are:

* Updating the docker every time to use the docker-compose `ver: 3.2` takes time
* The CI downloads the `faas-cli` every time
* The CI downloads the `templates` every time
* Does this work on Private Registries? (Theoretically, yes it should)
* Wish there was a `faas-cli push` to set a `tag name` (I wonder if there already is this option)

Any suggestions would be appreciated!
