### ISSUE TITLE
Feature: Add min/max scale for auto-scaling - Swarm & external providers

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#414]
Should be able to set a minimum scale for functions as well as the maximum (existing)

We can configure this through labels on the Docker Swarm service.

```
  labels:
    "com.openfaas.scale.min": "5"
    "com.openfaas.scale.max": "15"
```

Labels are generic so this would need faas-netes to expose some new data for the /system/function/<name> call too.

This will be useful for functions which are known to need to have high availability or traffic.

Implementation on Swarm:
* [x] Alert handler
* [x] Create handler
* [x] Update handler

cc @stefanprodan @ericstoekl 

Initial work: https://github.com/openfaas/faas/compare/scale_with_min_values?expand=1

**Comment by stefanprodan** [comment]
Tested on Kubernetes with the following stack:

```yml
functions:
  nodeinfo:
    handler: node main.js
    image: functions/nodeinfo:burner
    labels:
      com.openfaas.scale.min: "5"
      com.openfaas.scale.max: "15"
```

It got up to 15 PODs during the load test and down to 5 after that:

<img width="1026" alt="screen shot 2017-11-30 at 00 14 48" src="https://user-images.githubusercontent.com/3797675/33401898-980aff0e-d563-11e7-9c6d-8d058a93781d.png">
