### ISSUE TITLE
Getting "Cannot find service" when using host name other than localhost

### ISSUE THREAD

**Issue by andrewb-ms** [openfaas/faas#498]
Here is my file, artist.yml

```
provider:
  name: faas
  gateway: http://domainname.cloudapp.azure.com:8080

functions:
  artist:
    lang: Dockerfile
    handler: ./artist
    image: jmkhael/faas-artist:latest
    environment:
      TF_CPP_MIN_LOG_LEVEL: "3"
      read_timeout: "200"
      write_timeout: "200"
```

Expected: Can use cURL or PostMan to hit the public endpoint

Observed: Hitting localhost:8080 works fine, but the public endpoint does not work.

How to actually get this to attach to the public IP/domain name?  I also tried 0.0.0.0:8080 but that didn't work.

Full source code here: https://github.com/jmkhael/faas-artist
