### ISSUE TITLE
How to set Docker image version?

### ISSUE THREAD

**Issue by derailed** [openfaas/faas#522]
## Expected Behaviour

First off, thank you for your contributions and making this framework available to the community!

I am trying to put together some sample functions and running into issues with docs and general pilot errors... 

I would like to be able to version my docker images for my functions. It looks like images are being tagged as latest by default. I can not locate a good document that highlight the various tag available for the function.yaml. I thought this would be the place to indicate the docker image name and version. 
Also I need to be able to specify env variables in the yaml. Is this possible?

## Current Behaviour

My current understanding is that I can specify env vars using the deploy CLI but would like to set them
up in the function.yml.

I was hoping to be able to specify the following yaml config for my function

```yaml
provider:
  name:    faas
  gateway: ...

functions:
  fred:
    lang:    go
    handler: ./fred
    image:   fred
    version: v1
    labels:
      app: fred
    envs:
    - name:  MOVIE_DIC
      value: v2
```

## Steps to Reproduce (for bugs)

1. Define a function specification that configure env and imageVersion tags in the yaml
2.Deploy the function
3.Inspect the pod and see env vars and correct image tag being pull for a pod

## Context

Use Case: I need to be able to deploy several versions of the same function in order to test and rate the best implementation.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubenertes 1.9

* Operating System and version (e.g. Linux, Windows, MacOS):
OSX

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
