### ISSUE TITLE
Docker Swarm: test faas-swarm with TLS-enabled engine

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#574]
OpenFaaS should function with TLS-enabled engine, such as Docker CE or Docker EE.

## Task

* Generate self-signed certs
* Attempt to configure dockerd and docker client
* Configure `faas-swarm` or patch code to mount/use certificates rather than mounting socket from a manager
* Verify behavior
* Document all steps in Docker Swarm deployment guide

Looking for help with this

Docker's docs on TLS - https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl

**Comment by darknao** [comment]
Not sure what's the best way to do this, but here is what I've done in my case : 

My ca.pem cert.pem and key.pem are stored in my home directory (/home/pi/.docker) on my manager (redpi.home).
I've basically just mounted this directory and added a few environment variables in `docker-compose.armhf.yml` : 

 
```
[...]
    faas-swarm:
        volumes:
            - /home/pi/.docker:/certs
        environment:
            DOCKER_CERT_PATH: "/certs/"
            DOCKER_TLS_VERIFY: "1"
            DOCKER_HOST: "tcp://redpi.home:2376"
[...]
```
a (more generic?) alternative way is to use `tcp://172.18.0.1:2376` for `DOCKER_HOST` but it will require to add this specific IP to the server certificate (Subject Alternative Name).

**Comment by alexellis** [comment]
That sounds like a good approach. How did it go?

Is there a way to avoid a bind-mount such as by using swarm secrets or swarm configs?

cc @justincormack

**Comment by darknao** [comment]
Both method works fine. I currently use the second way.

Concerning the bind mount, I do like the swarm secrets approach.

Adding this at the end of the compose file : 

```
 secrets:
    ca.pem:
      file: /home/pi/.docker/ca.pem
    cert.pem:
      file: /home/pi/.docker/cert.pem
    key.pem:
      file: /home/pi/.docker/key.pem
```

then updating the `DOCKER_CERT_PATH` to `/run/secrets`
Works like a charm.

I do need to try this on a multi manager environment, though. But it should work.
