### ISSUE TITLE
How to define 2 functions under the same image?

### ISSUE THREAD

**Issue by dockerworxinc** [openfaas/faas#638]
I am new to OpenFaas. I have set it up on Ubuntu 16.10 running Docker 17.06. I am able to get it up and running under 8080 port under UI. Tried a simple python function and it was just quick without any issue.

May I know how shall I define 2 functions under the same image? TO be more clear, here is what I was trying out -

```
$tree
.
├── handler1.py
├── handler2.py
└── requirements.txt

0 directories, 3 files
```
```
==>cat handler1.py
def handle(req):
    print("Hello! You are in Handler1: " + req)
```
```
==>cat handler2.py
def handle(req):
    print("Hello! You are in Handler2: " + req)

```
```
$cat hello-python.yml


provider:
  name: faas
  gateway: http://192.168.24.10:8080

functions:
  handler1:
    lang: python
    handler: ./hello-python/handler1.py
    image: dockerworxinc/hello-python

  handler2:
    lang: python
    handler: ./hello-python/handler2.py
    image: dockerworxinc/hello-python
```

I am planning to include as many functions under the same Dockerhub image. Is this recommended?

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.06.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.10
