### ISSUE TITLE
Research: show GPU attached to a function

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#639]
## Description

Show a GPU attached to an OpenFaaS function in Kubernetes

## Background

We have several users using Python for data-science where GPU acceleration is available. From the investigation I've done so far we should be able to make a few minor changes to [faas-netes](https://github.com/openfaas/faas-netes/) and then be able to mount a GPU into a function.

## Tasks

* List compatible GPUs
* Write some code to mount a GPU
* Produce a short list of steps to document how to test the patches/PR
* Document any specific requirements / limitations

## Other notes

GKE has GPUs available pre-configured under Kubernetes - I think this would be the easiest way to test - https://thenewstack.io/getting-started-with-gpus-in-google-kubernetes-engine/

Otherwise you'll need an Nvidia GPU and the process for configuring your `kubelet` is not trivial

Documentation page from Kubernetes:

https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by LucasRoesler** [comment]
Per these docs https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

There are two core changes

1. There is a new schedulable resource `nvidia.com/gpu`, this is a required change.
2. it is possible to have mixed types of resources, so they recommend using node lables and node selectors to ensure that your pod ends up on the node with the specific GPU you are looking for (this is probably optional and very advanced).


The simplest example of a pod using a GPU is provided as 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
```

Note the `resources.limits`.  This field has very particular restrictions that are different from CPUs. These are listed as 

> * GPUs are only supposed to be specified in the limits section, which means:
> * You can specify GPU limits without specifying requests because Kubernetes will use the limit as the request value by default.
> * You can specify GPU in both limits and requests but these two values must be equal.
> * You cannot specify GPU requests without specifying limits.
> * Containers (and pods) do not share GPUs. There’s no overcommitting of GPUs.
> * Each container can request one or more GPUs. It is not possible to request a fraction of a GPU.

I think most of these changes will be made in the request struct and in the stack file schema https://github.com/openfaas/faas/blob/master/gateway/requests/requests.go#L47 and https://github.com/openfaas/faas-cli/blob/master/stack/schema.go#L50

Modifying the `FunctionRequests` struct would be the absolute minimum required change.

To support the mixed GPU case, we need to support allowing the developer to specify a `nodeSelector`, e.g.

```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    accelerator: nvidia-tesla-p100
```

This would be adding a new option to the http requests and the stack schema.
