### ISSUE TITLE
Question: Installing OpenFaaS on Swarm and Docker 17.05

### ISSUE THREAD

**Issue by CrystalMethod** [openfaas/faas#778]
I would like to use OpenFaaS on latest Synology - initially in single node Docker Swarm mode. But I'm not able to fully deploy the stack. The gateway restarts continuously and logs the error message "You must provide an external provider via 'functions_provider_url' env-var." I've reverted the "monitoring containers" to mounted configuration because of missing support of "configs" attribute. Additionally I reverted to docker-compose version 3.2 and changed the ``DOCKER_API_VERSION`` to 1.29

```yaml
version: "3.2"
services:
    gateway:
        ports:
            - 8082:8080
        image: openfaas/gateway:0.8.5
        networks:
            - functions
        environment:
            functions_provider_url: "http://faas-swarm:8080/"
            read_timeout:  "300s"        # Maximum time to read HTTP request
            write_timeout: "300s"        # Maximum time to write HTTP response
            upstream_timeout: "300s"     # Maximum duration of upstream function call - should be more than read_timeout and write_timeout
            dnsrr: "true"               # Temporarily use dnsrr in place of VIP while issue persists on PWD
            faas_nats_address: "nats"
            faas_nats_port: 4222
            direct_functions: "true"    # Functions are invoked directly over the overlay network
            direct_functions_suffix: ""
            basic_auth: "${BASIC_AUTH:-true}"
            secret_mount_path: "/run/secrets/"
        deploy:
            resources:
                # limits:   # Enable if you want to limit memory usage
                #     memory: 200M
                reservations:
                    memory: 100M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s
            placement:
                constraints:
                    - 'node.platform.os == linux'
        secrets:
            - basic-auth-user
            - basic-auth-password

    # Docker Swarm provider
    faas-swarm:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        # ports:
            # - 8081:8080
        image:  openfaas/faas-swarm:0.3.5
        networks:
            - functions
        environment:
            read_timeout:  "300s"   # set both here, and on your functions
            write_timeout: "300s"   # set both here, and on your functions
            DOCKER_API_VERSION: "1.29"
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                # limits:   # Enable if you want to limit memory usage
                #     memory: 100M
                reservations:
                    memory: 100M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s

    nats:
        image: nats-streaming:0.6.0
        # Uncomment the following port mappings if you wish to expose the
        # NATS client and/or management ports
        # ports:
        #     - 4222:4222
        #     - 8222:8222
        command: "--store memory --cluster_id faas-cluster"
        networks:
            - functions
        deploy:
            resources:
                limits:
                    memory: 125M
                reservations:
                    memory: 50M
            placement:
                constraints:
                    - 'node.platform.os == linux'

    queue-worker:
        image: openfaas/queue-worker:0.4.8
        networks:
            - functions
        environment:
            max_inflight: "1"
            ack_wait: "300s"    # Max duration of any async task / request
        deploy:
            resources:
                limits:
                    memory: 50M
                reservations:
                    memory: 20M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s
            placement:
                constraints:
                    - 'node.platform.os == linux'
    # End services

    # Start monitoring
    prometheus:
        image: prom/prometheus:v2.2.0
        environment:
            no_proxy: "gateway"
        volumes:
          - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
          - "./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml"
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        #   - '-storage.local.path=/prometheus'
        ports:
            - 9090:9090
        networks:
            - functions
        deploy:
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                limits:
                    memory: 500M
                reservations:
                    memory: 200M

    alertmanager:
        image: prom/alertmanager:v0.15.0-rc.0
        environment:
            no_proxy: "gateway"
        volumes:
          - "./prometheus/alertmanager.yml:/alertmanager.yml"
        command:
            - '--config.file=/alertmanager.yml'
            - '--storage.path=/alertmanager'
        networks:
            - functions
        # Uncomment the following port mapping if you wish to expose the Prometheus
        # Alertmanager UI.
        # ports:
        #     - 9093:9093
        deploy:
            resources:
                limits:
                   memory: 50M
                reservations:
                    memory: 20M
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
    # End monitoring
   
networks:
    functions:
        driver: overlay
        attachable: true
        labels:
          - "openfaas=true"

secrets:
    basic-auth-user:
        external: true
    basic-auth-password:
        external: true
```

## Context / Steps to Reproduce (for bugs)

There are several IPs and interfaces on that Synology. The given IP is a bonded network interface.

```
$ docker swarm init  --advertise-addr 192.168.1.2
Swarm initialized: current node (ms60omft2psr7u0jzf0oxk9ug) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token ... \
    192.168.1.2:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
```

```
$ ./deploy_stack.sh
Attempting to create credentials for gateway..
...
...
[Credentials]\n username: admin \n password: ...\n echo -n ... | faas-cli login --username=admin --password-stdin

Enabling basic authentication for gateway..

Deploying OpenFaaS core services
Creating network func_functions
Creating service func_faas-swarm
Creating service func_nats
Creating service func_queue-worker
Creating service func_prometheus
Creating service func_alertmanager
Creating service func_gateway
```

```
$docker ps
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS                  PORTS                                                                                                                                                                      NAMES
3ed350758d30        openfaas/gateway:0.8.5                               "./gateway"              6 seconds ago       Up Less than a second   8080/tcp                                                                                                                                                                   func_gateway.1.v1w5icylbhr0niuhxi7dsc8bv
22172a313c81        openfaas/queue-worker:0.4.8                          "./app"                  23 seconds ago      Up 15 seconds           8080/tcp                                                                                                                                                                   func_queue-worker.1.r05hcldti6r2t1kjpum1xge0e
7ac423a10487        prom/prometheus:v2.2.0                               "/bin/prometheus -..."   40 seconds ago      Up 20 seconds           9090/tcp                                                                                                                                                                   func_prometheus.1.wi0axlanb5xkekuy7tks9yg1f
b4de8736e84d        prom/alertmanager:v0.15.0-rc.0                       "/bin/alertmanager..."   41 seconds ago      Up 23 seconds           9093/tcp                                                                                                                                                                   func_alertmanager.1.56vp4afa28qlfkrcm7b35qocc
791922a3d0a2        nats-streaming:0.6.0                                 "/nats-streaming-s..."   58 seconds ago      Up 34 seconds           4222/tcp, 8222/tcp                                                                                                                                                         func_nats.1.qkbtjdukm0kh9yul48hl43161
2f78e351c49e        openfaas/faas-swarm:0.3.5                            "./faas-swarm"           59 seconds ago      Up 39 seconds           8080/tcp
```

```
$ docker logs 3ed350758d30
2018/07/20 08:23:36 HTTP Read Timeout: 8s
2018/07/20 08:23:36 HTTP Write Timeout: 8s
2018/07/20 08:23:36 You must provide an external provider via 'functions_provider_url' env-var.
```

```
$ docker logs 2f78e351c49e
2018/07/20 08:22:56 Docker API version: 1.29, 17.05.0-ce
2018/07/20 08:22:56 HTTP Read Timeout: 10s
2018/07/20 08:22:56 HTTP Write Timeout: 10s
```

## Your Environment

There is no (easy) chance to update one of the following.

```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   9f07f0e-synology
 Built:        Fri May 11 13:41:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
```

```
$ docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
