### ISSUE TITLE
YAML templating - always add tag to functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#779]
## Expected Behaviour

Functions are given an image without any tag, not even ":latest" or "0.1".

We should add one of the above to be explicit and encourage versioning.

Docker also has an odd feature discovered by @ivanayov where if you have multiple tags for an image and push without using a tag, all versions are pushed to the remote side.

## Current Behaviour

No tag is given, when you do a Docker push any tags associated with the image are pushed and that might not be the desired outcome. 

## Possible Solution

Pre-populate a tag in the YAML files via `faas-cli new`

Before:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  test:
    lang: go
    handler: ./test
    image: test
```

After:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  test:
    lang: go
    handler: ./test
    image: test:latest
```
