### ISSUE TITLE
Question: Memory size and disable autoscaling

### ISSUE THREAD

**Issue by white-cloud** [openfaas/faas#797]
Hello everyone, 

I want to ask you please how can i  fixe a specific  memory size for  the openfaas function ?
second question is how to desactivate the autoscaling ?.

Thank you.

**Comment by ivanayov** [comment]
Hi @white-cloud 

You can disable autoscaling by setting the min and max replicas to 1:
```
com.openfaas.scale.min: 1
com.openfaas.scale.max: 1
```

For memory limits you can use:
```
# Limits for function
limits:
  memory: 40m
# Requests of resources requested by function
requests:
  memory: 40m
```
