### ISSUE TITLE
expending template.yml file

### ISSUE THREAD

**Issue by ArieLevs** [openfaas/faas#799]
Hi,
functions are running as pods at openfaas-fn namespace,
but there is very poor ability to manipulate these pods, does that makes sense to provide ability to mount volumes to a faas framework?

is there an option to pass Kubernetes secrets as environment vars?

## Expected Behaviour
Able to use Kubernetes deployment syntax on template.yml
example 1: 
Have the ability to add `volumeMounts` and point it to a `persistentVolumeClaim` in the  template.yml file, does that makes sense on a faas?

Using encrypted environment variables
example 2:
Is there an option to provide environment secrets?
```
secrets:
    - secret-password <- need to be used as a env var
environment:
    write_debug: true
    blabla: "some value"
    
```

## Current Behaviour
poor ability to manipulate containers at openfaas-fn namespace

## Context
Using encrypted strings in my functions
Providing my function a local path

## Your Environment
* Docker version: 17.06.2-ce
* Kubernetes
* Operating System and version: Amazon Linux 2 (2017.12) (EKS Cluster)
